### ISSUE TITLE
not able to implment transformation 

### ISSUE THREAD

**Issue by csbug** [affanshahid/multer-storage-cloudinary#1]
how to apply transformation for image using this package.
i am not understanding how to crop or resize image and pass url to client 
eg url i want to pass is  as follow

http://res.cloudinary.com/doff7chku/image/upload/c_fill,h_900,q_50,w_1600/v1477502722/cover/104afcf9ea9a0bc7c470f62b8a50aa9b1477502739134.jpg

please help to understand  how to pass transformation parameter  **c_fill,h_900,q_50,w_1600**

i only manage to send file name as

http://res.cloudinary.com/doff7chku/image/upload/v1477502722/cover/104afcf9ea9a0bc7c470f62b8a50aa9b1477502739134.jpg

**Comment by affanshahid** [comment]
Previous implementation was invalid, needed a simple change for the type.
2b86f0a71a5e5d0153c90166ad7215600be97f37

Should work now as follows:
```javascript
var storage = cloudinaryStorage({
  cloudinary: cloudinary,
  folder: 'folder-name',
  allowedFormats: ['jpg', 'png'],
  transformation: function (req, file, cb) {
    var t = [
      {width: 400, height: 400, gravity: "face", radius: "max", crop: "crop"},
      {width: 200}
    ];
    cb(undefined, t);
  }
});
```
or by simply passing an array like `t` as the transformation parameter:
```javascript
var storage = cloudinaryStorage({
  cloudinary: cloudinary,
  folder: 'folder-name',
  allowedFormats: ['jpg', 'png'],
  transformation: [
    {width: 400, height: 400, gravity: "face", radius: "max", crop: "crop"},
    {width: 200}
]);
```
