### ISSUE TITLE
Pass aditional prop like "FolderName"

### ISSUE THREAD

**Issue by joaobibiano** [affanshahid/multer-storage-cloudinary#15]
Hi,

Im trying to send from the cliente a new parameter like "FolderName" to use it um return in params.

But, on the "file" parameter I only receive fieldname, originalname, encoding and mimeType

Theres is another way to do that?

Thanks

**Comment by affanshahid** [comment]
This is related to multer the `req` and `file` params are forwarded by multer so probably better to ask there. But if you want to access other params in the request you could use the `req` argument. Let me know if I misunderstood your question.

**Comment by joaobibiano** [comment]
> This is related to multer the `req` and `file` params are forwarded by multer so probably better to ask there. But if you want to access other params in the request you could use the `req` argument. Let me know if I misunderstood your question.

Thanks for the fast answer!

I solved this problem using a parameter on header requisition

I think we can close it
