### ISSUE TITLE
Format doesn't change

### ISSUE THREAD

**Issue by XavierColombel** [affanshahid/multer-storage-cloudinary#2]
I want to save images as png only.

When I try to change the format (jpg to png in my case) of an image, the final uploaded image is a jpg and not a png. Do you know how to change the format?

```
var avatar = cloudinaryStorage({
    cloudinary: cloudinary,
    folder: 'interface/user/avatar',
    allowedFormats: ['jpg', 'png'],
    format: 'png',
    transformation: [
        { width: 100, height: 100, crop: 'thumb', gravity: 'face' }
    ],
    filename: function (req, file, cb) {
        //console.log(file);
        cb(undefined, req.user._id + ".png");
    }
});
```

**Comment by affanshahid** [comment]
This has to do with the Cloudinary API. When using `allowed_formats` and `format` together only file types not included in `allowed_formats` will be converted to `format`. So simply removing 'jpg' from allowedFormats should work.

Source: https://support.cloudinary.com/hc/en-us/articles/205390662-Why-is-the-Format-parameter-inside-my-upload-preset-being-ignored-
