### ISSUE TITLE
Not able to upload video files

### ISSUE THREAD

**Issue by mikeng13** [affanshahid/multer-storage-cloudinary#4]
Uploading images works really well. Thanks for writing this plugin! 

However, when uploading video files, I get this in the console: `[object Object]` and nothing else and the video file is not uploaded to Cloudinary. I am uploading an mp4 file. Are there any special options I need to pass in?

**Comment by affanshahid** [comment]
According to: https://cloudinary.com/documentation/upload_videos

You would need `{ resource_type: "video" }`

So something like:
```
var cloudinary = require('cloudinary');
var cloudinaryStorage = require('multer-storage-cloudinary');

var storage = cloudinaryStorage({
  cloudinary: cloudinary,
    params: {
    folder: 'foo',
    format: 'mp4',
    resource_type: 'video'
  }
});
```
should work. Will test for myself when I get home.

Note: `resource_type` is not supported as a direct param to `CloudinaryStorage` so you will have to use the overriding `params` object like the example above. Should be added I suppose.

**Comment by affanshahid** [comment]
Have tested, videos are being uploaded correctly with the `resource_type` flag.
