### ISSUE TITLE
Remove images

### ISSUE THREAD

**Issue by jonathanmorales990** [affanshahid/multer-storage-cloudinary#6]
How to remove a image?

**Comment by zuber1077** [comment]
you can use normal `cloudinary.v2.uploader.destroy(public_id);`
you need cloudinary package to do that `const = cloudinary = require("cloudinary")`

**Comment by affanshahid** [comment]
The storage engine removes file in case of errors autmatically. If you want to manually remove files as needed use the suggestion by @zuber1077
