### ISSUE TITLE
What is the default value and accepted values of options.type value?

### ISSUE THREAD

**Issue by mahdiarn** [affanshahid/multer-storage-cloudinary#7]
What is the default value of that options? The documentation said that it was accepting string or function, is it "upload" if it is a string?
For the accepted values i assume it was from cloudinary upload API and the accepted value for string type is "Upload", "Rename", "Destroy", "Tags", "Context", "Explicit", "Explode", etc. Is it correct?

**Comment by affanshahid** [comment]
Yes your assumption is correct. The library doesn't set any defaults itself. All defaults come from the cloudinary API
